name: Python Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.13-dev"]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          allow-prereleases: true
      - name: Install system packages
        run: |
          sudo apt-get update
          sudo apt-get install -y libxcb-cursor0 libxkbcommon-x11-0 libegl1
      - name: Install dependencies
        run: |
          pip install .[dev] --pre
      - name: Run pre-commit
        run: |
          files=$(git diff --name-only HEAD^ -- '*.py')
          if [ -n "$files" ]; then
            pre-commit run --files $files
          fi
      - name: Run tests
        run: pytest
