name: Windows Installer

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build-msi:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13-dev'
      - name: Install uv
        shell: bash
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "$HOME/.local/bin" >> $GITHUB_PATH
      - name: Install dependencies
        shell: bash
        run: uv sync --extra dev
      - name: Install WiX Toolset
        run: choco install wixtoolset --yes
      - name: Build installer
        shell: bash
        run: make build-msi
      - name: Verify checksums
        shell: bash
        run: |
          cd dist
          sha256sum -c SHA256SUMS
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: bang-msi
          path: |
            dist/bang.msi
      - name: Attach to release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/bang.msi
